# Generated by Django 4.2.19 on 2025-02-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('per_day_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seating_capacity', models.IntegerField()),
                ('additional_km_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('allow_daily', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pickmeapp.vehicle')),
            ],
        ),
    ]
