# Generated by Django 4.2.19 on 2025-02-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickmeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='additional_km_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seating_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
