# Generated by Django 4.2.19 on 2025-02-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickmeapp', '0002_remove_vehicleimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='allow_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seating_capacity',
            field=models.IntegerField(),
        ),
    ]
