# Generated by Django 4.2.19 on 2025-02-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickmeapp', '0005_vehicle_created_at_vehicle_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehicleimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='vehicleimage',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='additional_km_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='per_day_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicle_images/'),
        ),
    ]
