# Generated by Django 4.2.19 on 2025-03-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickmeapp', '0006_remove_vehicle_created_at_remove_vehicle_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
