# Generated by Django 4.2.19 on 2025-03-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickmeapp', '0007_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
